# Cloudflare Pages 配置
name = "fcl-docs"
compatibility_date = "2023-10-30"

# Pages 特定配置
[build]
command = "bash ./build.sh"
publish = "."

[build.upload]
format = "directory"
dir = "."

[site]
bucket = "."
entry-point = "."

[build.environment]
NODE_VERSION = "18" 